CREATE TABLE series (
ID INTEGER PRIMARY KEY,
TITLE TEXT,
AUTHOR_ID INTEGER,
SUBGENRE_ID INTEGER);

CREATE TABLE subgenres (
ID INTEGER PRIMARY KEY,
NAME TEXT);

CREATE TABLE authors (
ID INTEGER PRIMARY KEY,
NAME TEXT);

CREATE TABLE books (
ID INTEGER PRIMARY KEY,
TITLE TEXT,
YEAR INTEGER,
SERIES_ID INTEGER);

CREATE TABLE characters (
ID INTEGER PRIMARY KEY,
NAME TEXT,
MOTTO TEXT,
SPECIES TEXT,
AUTHOR_ID INTEGER);

CREATE TABLE character_books (
ID INTEGER PRIMARY KEY,
BOOK_ID INTEGER,
CHARACTER_ID INTEGER);
